# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'treena_v2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for treena_v2
pod 'SnapKit', '~> 5.0.0'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'

end
